name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: subtitle-editor-srmd-frontend@master
        with:
          owner: nidhishah-seva
          repo: subtitle-editor-srmd-backend
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: deploy.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
